version: '3.8'

volumes:
  postgres_data:

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "psql", "-U", "postgres", "-c", "SELECT 1;" ]
      interval: 1m
      timeout: 10s
      retries: 5

  keycloak:
    image: bitnami/keycloak:22.0.1-debian-11-r25
    environment:
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.migration.action=import
                            -Dkeycloak.migration.realmName=annotto
                            -Dkeycloak.migration.provider=dir
                            -Dkeycloak.migration.dir=/opt/bitnami/keycloak/data/import
                            -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
                            -Dkeycloak.migration.usersExportStrategy=SAME_FILE
                            -Dkeycloak.profile.feature.upload_scripts=enabled"
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      # To pre-configured keycloak with data
      - ./statics/keycloak:/opt/bitnami/keycloak/data/import
    depends_on:
      - postgresql
    restart: always
    ports:
      - "8080:8080"
#      - 443:8443

  minio:
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage/minio:/data
    restart: unless-stopped

  mongo:
    image: "mongo:4.4"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --host mongo:27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s
