name: Push to Dependency-Track

on:
  release:
    types: [released]


jobs:
  push-to-dt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Generate SBOM
        uses: CycloneDX/gh-node-module-generatebom@master
        with:
          output: './bom.xml'
      - name: Push to DT
        run: |
          curl -X 'POST' 'https://dependency-track.ops.lajavaness.com/api/v1/bom' -H 'X-API-Key:${{ secrets.DT_API_KEY }}' -H 'Content-Type: multipart/form-data' -F 'bom=@bom.xml' -F 'project=7b01815b-08f2-430e-96a4-1ccb4aa52f40'

